[package]
name = "labelmaker"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
eframe = "0.22.0"
pico-args = "0.5"
rand = "0.8.5"
tempfile = "3.6.0"

[features]
default = ["eq-separator"]
eq-separator = ["pico-args/eq-separator"]
